spring:
  application:
    name: discogs-stats
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}


  liquibase:
    change-log: classpath:db/changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
